AWSTemplateFormatVersion: "2010-09-09"

Resources:
  ServicesAdminDutiesBeta:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: SERVICES_ADMIN_DUTIES_BETA
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
