version: "3.3"

services:
  dynamo-db-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: " -jar DynamoDBLocal.jar -sharedDb -dbPath ."

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - dynamo-db-local
    environment:
      AWS_DEFAULT_PROFILE: dynamo-db-local
      AWS_ENDPOINT: --endpoint-url=http://dynamo-db-local:8000
    entrypoint: /bin/sh -c
    volumes:
      - "./database/init-scripts:/init-scripts"
      - "./database/data:/data"
    command: >
      '
       for script_name in /init-scripts/*.sh; do
         sh $$script_name
       done
      '